/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ControllersCompanyControllerRouteImport } from './routes/controllers.$company.$controller'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControllersCompanyControllerRoute =
  ControllersCompanyControllerRouteImport.update({
    id: '/controllers/$company/$controller',
    path: '/controllers/$company/$controller',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/controllers/$company/$controller': typeof ControllersCompanyControllerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/controllers/$company/$controller': typeof ControllersCompanyControllerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/controllers/$company/$controller': typeof ControllersCompanyControllerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/controllers/$company/$controller'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/controllers/$company/$controller'
  id: '__root__' | '/' | '/controllers/$company/$controller'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControllersCompanyControllerRoute: typeof ControllersCompanyControllerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controllers/$company/$controller': {
      id: '/controllers/$company/$controller'
      path: '/controllers/$company/$controller'
      fullPath: '/controllers/$company/$controller'
      preLoaderRoute: typeof ControllersCompanyControllerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControllersCompanyControllerRoute: ControllersCompanyControllerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
